package server
import("encoding/json";"net/http";"strconv";"github.com/stockyard-dev/stockyard-headcount/internal/store")
func(s *Server)handleListDepts(w http.ResponseWriter,r *http.Request){list,_:=s.db.ListDepartments();if list==nil{list=[]store.Department{}};writeJSON(w,200,list)}
func(s *Server)handleCreateDept(w http.ResponseWriter,r *http.Request){var d store.Department;json.NewDecoder(r.Body).Decode(&d);if d.Name==""{writeError(w,400,"name required");return};if err:=s.db.CreateDepartment(&d);err!=nil{writeError(w,500,err.Error());return};writeJSON(w,201,d)}
func(s *Server)handleDeleteDept(w http.ResponseWriter,r *http.Request){id,_:=strconv.ParseInt(r.PathValue("id"),10,64);s.db.DeleteDepartment(id);writeJSON(w,200,map[string]string{"status":"deleted"})}
func(s *Server)handleListEmployees(w http.ResponseWriter,r *http.Request){deptID,_:=strconv.ParseInt(r.URL.Query().Get("dept_id"),10,64);list,_:=s.db.ListEmployees(deptID);if list==nil{list=[]store.Employee{}};writeJSON(w,200,list)}
func(s *Server)handleCreateEmployee(w http.ResponseWriter,r *http.Request){var e store.Employee;json.NewDecoder(r.Body).Decode(&e);if e.FirstName==""||e.LastName==""{writeError(w,400,"first_name and last_name required");return};if e.Status==""{e.Status="active"};if err:=s.db.CreateEmployee(&e);err!=nil{writeError(w,500,err.Error());return};writeJSON(w,201,e)}
func(s *Server)handleUpdateEmployee(w http.ResponseWriter,r *http.Request){id,_:=strconv.ParseInt(r.PathValue("id"),10,64);var req struct{Status string `json:"status"`};json.NewDecoder(r.Body).Decode(&req);if req.Status==""{writeError(w,400,"status required");return};if err:=s.db.UpdateEmployeeStatus(id,req.Status);err!=nil{writeError(w,500,err.Error());return};writeJSON(w,200,map[string]string{"status":"updated"})}
func(s *Server)handleDeleteEmployee(w http.ResponseWriter,r *http.Request){id,_:=strconv.ParseInt(r.PathValue("id"),10,64);s.db.DeleteEmployee(id);writeJSON(w,200,map[string]string{"status":"deleted"})}
func(s *Server)handleListLeave(w http.ResponseWriter,r *http.Request){status:=r.URL.Query().Get("status");list,_:=s.db.ListLeaveRequests(status);if list==nil{list=[]store.LeaveRequest{}};writeJSON(w,200,list)}
func(s *Server)handleCreateLeave(w http.ResponseWriter,r *http.Request){var l store.LeaveRequest;json.NewDecoder(r.Body).Decode(&l);if l.EmployeeID==0||l.StartDate==""||l.EndDate==""{writeError(w,400,"employee_id, start_date, end_date required");return};if l.LeaveType==""{l.LeaveType="vacation"};if err:=s.db.CreateLeaveRequest(&l);err!=nil{writeError(w,500,err.Error());return};writeJSON(w,201,l)}
func(s *Server)handleUpdateLeave(w http.ResponseWriter,r *http.Request){id,_:=strconv.ParseInt(r.PathValue("id"),10,64);var req struct{Status string `json:"status"`};json.NewDecoder(r.Body).Decode(&req);if req.Status==""{writeError(w,400,"status required");return};s.db.UpdateLeaveStatus(id,req.Status);writeJSON(w,200,map[string]string{"status":"updated"})}
func(s *Server)handleStats(w http.ResponseWriter,r *http.Request){emp,_:=s.db.CountEmployees();pend,_:=s.db.CountPending();writeJSON(w,200,map[string]interface{}{"active_employees":emp,"pending_leave":pend})}
